In [1]:
#importing lib
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import HuberRegressor
from sklearn.metrics import mean_squared_error
import pickle as pk
#step-1 load dataset
dataset =  pd.read_csv("C:/Users/balar/Desktop/AI/Machine_learning/Advertising.csv",index_col=0)
dataset.head()

TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [2]:
inputFeature = ['TV', 'radio', 'newspaper']
outputFeature = ['sales']
x = dataset[inputFeature]
y = dataset[outputFeature]
x.head()

TV  radio  newspaper
1  230.1   37.8       69.2
2   44.5   39.3       45.1
3   17.2   45.9       69.3
4  151.5   41.3       58.5
5  180.8   10.8       58.4

In [3]:
y.head()
#step-2 split dataset
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=3)

In [4]:
x.shape

(200, 3)

In [5]:
xtrain.shape


(160, 3)

In [6]:
xtest.shape


(40, 3)

In [7]:
xtrain.head()

TV  radio  newspaper
157   93.9   43.5       50.5
116   75.1   35.0       52.7
156    4.1   11.6        5.7
16   195.4   47.7       52.9
62   261.3   42.7       54.7

In [8]:
#step-3 model defining
model = HuberRegressor()
#step-4 training
model.fit(xtrain,ytrain)

c:\users\balar\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False)

In [9]:
#step-7 testing
ypred = model.predict(xtest)
#metrics
error = np.sqrt(mean_squared_error(ytest,ypred))
error

1.4505323795493397

In [17]:
test = [151.5,41.3,58.5] # output => 18.5
model.predict([test])

array([17.98177198])

In [18]:
model.coef_

array([ 0.04254397,  0.1993283 , -0.00132803])

In [19]:
model.intercept_

3.381791690780346

In [20]:
value = 0
for x,b in zip(test,[0.04552917, 0.18512403, 0.00119881]):
     value += (x*b)

In [24]:
# model file creation
pk.dump(model,open("icebergModel.model","wb"))
import pickle as pk
loadedModel = pk.load(open("icebergModel.model","rb"))
loadedModel.predict([test])

array([17.98177198])

In [10]:
error/18.5

0.07840715565131566